version: '3.8'

services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - docker-compose-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - docker-compose-network

volumes:
  mysql_data:

networks:
  docker-compose-network:
    driver: bridge

